apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  namespace: causality
spec:
  selector:
    matchLabels:
      app: core
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: core
    spec:
      initContainers:
        - name: run-migrations
          image: ghcr.io/causality-africa/core:latest
          imagePullPolicy: Always
          command: ["/tern", "migrate", "--migrations", "migrations"]
          env:
            - name: CORE_API_PORT
              value: "8080"
            - name: CORE_DB_HOST
              value: "postgres-svc.causality.svc.cluster.local"
            - name: CORE_DB_PORT
              value: "5432"
            - name: CORE_DB_NAME
              value: causality
            - name: CORE_DB_USER
              value: causality
            - name: CORE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env
                  key: POSTGRES_PASSWORD
      containers:
        - name: core
          image: ghcr.io/causality-africa/core:latest
          imagePullPolicy: Always
          env:
            - name: CORE_API_PORT
              value: "8080"
            - name: CORE_DB_HOST
              value: "postgres-svc.causality.svc.cluster.local"
            - name: CORE_DB_PORT
              value: "5432"
            - name: CORE_DB_NAME
              value: causality
            - name: CORE_DB_USER
              value: causality
            - name: CORE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
