apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: causality
data:
  AIRFLOW__CORE__EXECUTOR: "KubernetesExecutor"
  AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags/collector"
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE: "causality"
  AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_REPOSITORY: "ghcr.io/causality-africa/collector"
  AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_TAG: "v0.2.9"
  AIRFLOW__KUBERNETES_EXECUTOR__POD_TEMPLATE_FILE: "/opt/airflow/pod_template.yaml"
  AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS: "True"
  AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS_ON_FAILURE: "False"
  AIRFLOW__KUBERNETES_EXECUTOR__DELETE_OPTION_KWARGS: '{"grace_period_seconds": 30}'
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "False"
