apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airflow-ingress
  namespace: causality
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - airflow
  rules:
    - host: airflow
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: airflow-webserver-svc
                port:
                  number: 8080
