apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-pod-template
  namespace: causality
data:
  pod_template.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: airflow-worker-pod
      labels:
        app: airflow-worker
    spec:
      restartPolicy: Never
      containers:
        - name: airflow-worker
          image: ghcr.io/causality-africa/collector:v0.2.7
          envFrom:
            - configMapRef:
                name: airflow-config
          env:
            - name: B2_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: B2_ACCESS_KEY_ID
            - name: B2_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: env
                  key: B2_SECRET_ACCESS_KEY
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env
                  key: POSTGRES_PASSWORD
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://causality:$(POSTGRES_PASSWORD)@postgres-svc.causality.svc.cluster.local:5432/causality
          volumeMounts:
            - name: dags-volume
              mountPath: /opt/airflow/dags
      volumes:
        - name: dags-volume
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
