apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  namespace: causality
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow
  namespace: causality
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow
  namespace: causality
subjects:
  - kind: ServiceAccount
    name: airflow
    namespace: causality
roleRef:
  kind: Role
  name: airflow
  apiGroup: rbac.authorization.k8s.io
