apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: causality
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      initContainers:
        - name: init-db
          image: ghcr.io/causality-africa/collector:v0.2.0
          command: ["airflow", "db", "init"]
          envFrom:
            - configMapRef:
                name: airflow-config
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://causality:$(POSTGRES_PASSWORD)@postgres-svc.causality.svc.cluster.local:5432/causality
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env
                  key: POSTGRES_PASSWORD
      containers:
        - name: airflow-webserver
          image: ghcr.io/causality-africa/collector:v0.2.0
          ports:
            - containerPort: 8080
          command: ["airflow", "webserver"]
          envFrom:
            - configMapRef:
                name: airflow-config
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://causality:$(POSTGRES_PASSWORD)@postgres-svc.causality.svc.cluster.local:5432/causality
            - name: AIRFLOW__WEBSERVER__SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: env
                  key: AIRFLOW_WEBSERVER_SECRET_KEY
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: pod-template
              mountPath: /opt/airflow/pod_template.yaml
              subPath: pod_template.yaml
            - name: dags-volume
              mountPath: /opt/airflow/dags
      volumes:
        - name: pod-template
          configMap:
            name: airflow-pod-template
        - name: dags-volume
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
