apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
  namespace: causality
spec:
  serviceName: valkey-svc
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:8.0.2
          args:
            - "--save"
            - "300"
            - "1"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: valkey-data
              mountPath: /data
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: valkey-data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
